### ISSUE TITLE
issue updating to 0.18

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/deathinspace-foundry-vtt#21]
Since 0.18 was pushed, foundry cannot update. https://github.com/fvtt-fria-ligan/deathinspace-foundry-vtt/releases/latest/download/system.json has file not found.

**Comment by mcglincy** [comment]
Seems like the github workflow missed adding some files. I created a new 0.18.1 that now includes system.json. Can you verify that works OK for you @r-valyar ?

**Comment by r-valyar** [comment]
Yes, I manage to update, thanks! 

![image](https://user-images.githubusercontent.com/63558984/160697159-ecaa77bf-102f-4c90-bf75-aab130e1c3d1.png)

**Comment by mcglincy** [comment]
Awesome; closing this issue.
