### ISSUE TITLE
Impossible to duplicate an actor

### ISSUE THREAD

**Issue by JhaelenTerear** [fvtt-fria-ligan/deathinspace-foundry-vtt#30]
Hi,

When I try to right click > duplicate an actor, it doesn't do anything and an error pops in the console.

![image](https://user-images.githubusercontent.com/58259514/201034200-996e21c7-b6c2-438a-a364-c7cf1441005f.png)
![image](https://user-images.githubusercontent.com/58259514/201033599-8feab3a7-d91e-4740-bda8-d08808fc17d7.png)

**Comment by mcglincy** [comment]
Sorry, didn't see the notification of this issue. I'll take a look! (and, it's possible this was fixed in 2.0.2)

**Comment by mcglincy** [comment]
I believe this is working in the latest system version.
