### ISSUE TITLE
Equippable Items not working for NPCs

### ISSUE THREAD

**Issue by MulliganStu** [fvtt-fria-ligan/deathinspace-foundry-vtt#41]
Following these steps:

1. Generate an NPC
2. Open their inventory
3. Drag anything with the equippable option (ie. armor) onto their character sheet

Results in:

1. No item is placed into their inventory. 
2. Unable to reopen the character sheet once more. 

Looking at the console, I see the following error:

![image](https://github.com/user-attachments/assets/3f099638-a758-4efa-bccc-12bed70563c0)

I am currently using version 4.0.0

If you require any additional information I am happy to provide it.

**Comment by coderunner** [comment]
Encounter this error this week. 

#43 fixes it
